export const UNDER_CANDIDATE = "UNDER CANDIDATE PROGRESS";
export const UNDER_QA = "UNDER QA REVIEW";
export const COMPLETED = "COMPLETED";
export const ABUSIVE_OR_SENSELESS_SENTENCE = "ABUSIVE SENTENCE OR SENSELESS SENTENCE";
export const LANGUAGE_CODE_MAP = {
  ASSAMESE: "AS",
  BENGALI: "BN",
  BODO: "BO",
  DOGRI: "DO",
  GUJARATI: "GU",
  HINDI: "HI",
  KANNADA: "KN",
  KASHMIRI: "KS",
  KONKANI: "KO",
  MAITHILI: "MA",
  MALAYALAM: "ML",
  MANIPURI: "MN",
  MARATHI: "MR",
  NEPALI: "NE",
  ODIA: "OR",
  PUNJABI: "PA",
  SANSKRIT: "SA",
  SANTHALI: "ST",
  SINDHI: "SD",
  TAMIL: "TA",
  TELUGU: "TE",
  URDU: "UR",
  ENGLISH: "EN", // commonly used in governance and education
};

